//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garcon.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class billitem
    {
        public int id { get; set; }
        public int billid { get; set; }
        public int itemid { get; set; }
        public int seatnum { get; set; }
    
        public virtual bill bill { get; set; }
        public virtual item item { get; set; }
    }
}
