//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garcon.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public bill()
        {
            this.billitems = new HashSet<billitem>();
        }
    
        public int id { get; set; }
        public int tableid { get; set; }
        public bool paid { get; set; }
        public System.DateTime checkedin { get; set; }
        public Nullable<System.DateTime> checkedout { get; set; }
    
        public virtual ICollection<billitem> billitems { get; set; }
        public virtual table table { get; set; }
    }
}
