//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garcon.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public item()
        {
            this.billitems = new HashSet<billitem>();
        }
    
        public int id { get; set; }
        public int restaurantid { get; set; }
        public string description { get; set; }
        public decimal price { get; set; }
    
        public virtual ICollection<billitem> billitems { get; set; }
        public virtual restaurant restaurant { get; set; }
    }
}
