//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garcon.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class restaurant
    {
        public restaurant()
        {
            this.items = new HashSet<item>();
            this.tables = new HashSet<table>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public System.Data.Spatial.DbGeography loc { get; set; }
        public string img { get; set; }
    
        public virtual ICollection<item> items { get; set; }
        public virtual ICollection<table> tables { get; set; }
    }
}
