//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garcon.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class table
    {
        public table()
        {
            this.bills = new HashSet<bill>();
        }
    
        public int id { get; set; }
        public int restaurantid { get; set; }
        public string beaconid { get; set; }
    
        public virtual ICollection<bill> bills { get; set; }
        public virtual restaurant restaurant { get; set; }
    }
}
